---
name: Bug Report
description: File a bug report.
title: "[Bug] "
labels:
  - bug
  - unconfirmed
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: textarea
    id: what-happened
    attributes:
      label: What happened? What are the steps to reproduce the issue?
      description: >-
        Describe the bug and include the steps to replicate the issue. Issues
        with images or videos will be resolved faster.
      placeholder: Clearly explain the issue. Please limit each post to one issue.
    validations:
      required: true

  - type: textarea
    id: expected-behaviour
    attributes:
      label: What did you expect to happen?
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true

  - type: dropdown
    id: version
    attributes:
      label: NudgeNotch Version
      description: >-
        What version of NudgeNotch are you running? (Check in the menu bar or
        Settings > About)
      options:
        - Select a version
        - v0.3.8
        - v0.3.7
        - v0.3.0
        - v0.2.3
    validations:
      required: true

  - type: input
    id: operating-system
    attributes:
      label: macOS Version
      description: "Go to Apple menu () > About This Mac"
    validations:
      required: true

  - type: dropdown
    id: mac-type
    attributes:
      label: Mac Type
      description: What kind of Mac are you using?
      options:
        - MacBook with notch (Apple Silicon)
        - MacBook without notch
        - Desktop Mac (iMac, Mac Mini, etc.)
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: >-
        Please copy and paste any relevant log output from Console.app.
        This will be automatically formatted into code, so no need for backticks.
      render: shell

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots / Screen recordings
      description: >-
        If applicable, add screenshots or recordings to help explain the issue.
        You can drag and drop images directly into this field.

  - type: checkboxes
    id: checks
    attributes:
      label: Checks
      options:
        - label: I haven't found any duplicates of this issue.
          required: true
